default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: colorroll_development

test:
  <<: *default
  database: colorroll_test
